# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest
  # name: 'MartinsXPS15'
  # demands:
  #   - agent.name -equals MARTINS_XPS15

#https://learn.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml
#stages is a logical group of jobs
#Stages run by default sequentially and you can use dependencies and conditions
variables:
  buildConfiguration: 'Release'

stages:
  - stage: buildStage 
    jobs:
    - job: showDirectory
      displayName: 'show directory and files'
      timeoutInMinutes: 10
      steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              # Write your commands here
              echo 'Directory'
              pwd
              echo 'Files'
              ls -l
              echo 'Project directory'
              cd AppSimple
              ls -l

    - job: buildDotnet
      displayName: 'dotnet build $(buildConfiguration)'
      steps:
        - script: dotnet build --configuration $(buildConfiguration)

  - stage: runStage 
    jobs:
    - job: runAppSimple
      displayName: 'dotnet run' 
      timeoutInMinutes: 10
      steps:
        - script: dotnet run --project AppSimple/AppSimple.csproj
       #- bash: exit 1  #This step will now fail
  
  - stage: finalStage 
    dependsOn: 
    - buildStage 
    - runStage 
    jobs:
    - job: finalJob
      displayName: 'finalJob' 
      timeoutInMinutes: 10
      steps:
      - bash: echo "Executing finalJob"
