# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest
  # name: 'MartinsXPS15'
  # demands:
  #   - agent.name -equals MARTINS_XPS15

#https://learn.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml
#Multiple jobs will run in parallell if possible
jobs:
- job: myJobA
  displayName: 'myJobA saying Hello World' 
  timeoutInMinutes: 10
  steps:
  - bash: echo "Hello world from myJobA"
  - bash: echo "Hello world from myJobA"

- job: myJobB
  displayName: 'myJobB saying Hello World' 
  timeoutInMinutes: 10
  steps:
  - bash: echo "Hello world from myJobB"
  - bash: echo "Hello world from myJobB"